exclude: .*/test/data/|.clang-format
repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v14.0.1
    hooks:
      - id: clang-format
  - repo: https://gitlab.com/pycqa/flake8.git
    rev: 3.8.3
    hooks:
      - id: flake8
  - repo: https://github.com/asottile/seed-isort-config.git
    rev: v2.2.0
    hooks:
      - id: seed-isort-config
        args: [--settings-path, ./]
  - repo: https://github.com/PyCQA/isort.git
    rev: 5.10.1
    hooks:
      - id: isort
        args: [--settings-file, ./setup.cfg]
  - repo: https://github.com/pre-commit/mirrors-yapf.git
    rev: v0.30.0
    hooks:
      - id: yapf
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v3.1.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        exclude: .*/test/data/
      - id: check-yaml
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: double-quote-string-fixer
      - id: check-merge-conflict
      - id: fix-encoding-pragma
        args: ["--remove"]
      - id: mixed-line-ending
        args: ["--fix=lf"]
  - repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
      - id: codespell
  - repo: https://github.com/myint/docformatter.git
    rev: v1.3.1
    hooks:
      - id: docformatter
        args: ["--in-place", "--wrap-descriptions", "79"]
